import { lift2, lift1 } from "@synx/frp/reactive";

export const add = lift2((a: number, b: number) => a + b);
export const sub = lift2((a: number, b: number) => a - b);
export const mul = lift2((a: number, b: number) => a * b);
export const div = lift2((a: number, b: number) => a / b);
export const mod = lift2((a: number, b: number) => a % b);
export const min = lift2(Math.min);
export const max = lift2(Math.max);
export const abs = lift1(Math.abs);
export const floor = lift1(Math.floor);
export const ceil = lift1(Math.ceil);
export const round = lift1(Math.round);
export const sqrt = lift1(Math.sqrt);
export const pow = lift2(Math.pow);
export const exp = lift1(Math.exp);
export const log = lift1(Math.log);
export const sin = lift1(Math.sin);
export const cos = lift1(Math.cos);
export const tan = lift1(Math.tan);
export const asin = lift1(Math.asin);
export const acos = lift1(Math.acos);
export const atan = lift1(Math.atan);
export const atan2 = lift2(Math.atan2);
export const sinh = lift1(Math.sinh);
export const cosh = lift1(Math.cosh);
export const tanh = lift1(Math.tanh);
export const asinh = lift1(Math.asinh);
export const acosh = lift1(Math.acosh);
export const atanh = lift1(Math.atanh);
