import { Reactive } from "@synx/frp";

export const add = Reactive.lift2((a: number, b: number) => a + b);
export const sub = Reactive.lift2((a: number, b: number) => a - b);
export const mul = Reactive.lift2((a: number, b: number) => a * b);
export const div = Reactive.lift2((a: number, b: number) => a / b);
export const mod = Reactive.lift2((a: number, b: number) => a % b);
export const min = Reactive.lift2(Math.min);
export const max = Reactive.lift2(Math.max);
export const abs = Reactive.lift1(Math.abs);
export const floor = Reactive.lift1(Math.floor);
export const ceil = Reactive.lift1(Math.ceil);
export const round = Reactive.lift1(Math.round);
export const sqrt = Reactive.lift1(Math.sqrt);
export const pow = Reactive.lift2(Math.pow);
export const exp = Reactive.lift1(Math.exp);
export const log = Reactive.lift1(Math.log);
export const sin = Reactive.lift1(Math.sin);
export const cos = Reactive.lift1(Math.cos);
export const tan = Reactive.lift1(Math.tan);
export const asin = Reactive.lift1(Math.asin);
export const acos = Reactive.lift1(Math.acos);
export const atan = Reactive.lift1(Math.atan);
export const atan2 = Reactive.lift2(Math.atan2);
export const sinh = Reactive.lift1(Math.sinh);
export const cosh = Reactive.lift1(Math.cosh);
export const tanh = Reactive.lift1(Math.tanh);
export const asinh = Reactive.lift1(Math.asinh);
export const acosh = Reactive.lift1(Math.acosh);
export const atanh = Reactive.lift1(Math.atanh);
